version: "3"
services:
  chrome_node:
    image: selenium/node-chrome:4.11.0
    container_name: chrome_node
    shm_size: 2gb
    depends_on:
      - selenium_hub
    environment:
      - SE_NODE_GRID_URL=http://localhost:4444
      - SE_EVENT_BUS_HOST=selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_SESSION_TIMEOUT=60
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
  selenium_hub:
    image: selenium/hub:4.11.0
    container_name: selenium_hub
    ports:
      - "4444:4444"