name: "Make a war"

env:
  ####### ENV VARS #######
  SEC_PHRASE: ${{ secrets.SEC_PHRASE }}
  SEC_PHRASE_2: ${{ secrets.SEC_PHRASE_2 }}
  SEC_PHRASE_3: ${{ secrets.SEC_PHRASE_3 }}
  SEC_PASSWORD: ${{ secrets.SEC_PASSWORD }}
  SEC_GAME_URL: ${{ secrets.SEC_GAME_URL }}
  SEC_GAME_URL_CAMP: ${{ secrets.SEC_GAME_URL_CAMP }}
  SEC_GAME_URL_OPPONENTS_CAMP: ${{ secrets.SEC_GAME_URL_OPPONENTS_CAMP }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Start selenium grid
        run: docker-compose -f selenium-compose.yaml up -d

      - name: Build and run
        run: mvn -T 2 test -Dbrowser='chrome' "-Djunit.jupiter.execution.parallel.enabled=true"