name: "Make a war"

env:
  ####### ENV VARS #######
  SEC_PHRASE: ${{ secrets.SEC_PHRASE }}
  SEC_PASSWORD: ${{ secrets.SEC_PASSWORD }}


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Start selenium grid
        run: docker-compose -f selenium-compose.yaml up -d

      - name: Build and run
        run: mvn test -Dbrowser='chrome'

      - name: Upload screenshot
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: ./screenshots/
          retention-days: 5
          if-no-files-found: error